name: "GamePooling"
main: "com.dami.gamepooling.GamePooling"
version: "1.0.0"
api-version: "1.18"
commands:
    queue:
        description: join a queue
        usage: queue <join|leave|help|info> <queue name>
